### ISSUE TITLE
Why do we clone args?

### ISSUE THREAD

**Issue by trusktr** [Mr0grog/newless#13]
https://github.com/Mr0grog/newless/blob/3fe059f3f8ac26d945afb01c880dd68d2e61d631/newless.js#L48

Why do we copy the array here, and in the non-spreadable version we don't?

**Comment by Mr0grog** [comment]
Just because a browser supports the spread operator does not mean the operator works on all the kinds of objects it’s supposed to!

In Safari 8, the spread operator did not work with a wide variety of iterable objects, including the `arguments` object (this library was written in the Safari 8/9 timeframe). Safari 9 also had some issues with spread, but I don’t remember whether usage with the `arguments` object had been fixed. Earlier versions of MS Edge also had incomplete implementations of spread.
