### ISSUE TITLE
Why not set `prototype.constructor = newlessConstructor`?

### ISSUE THREAD

**Issue by trusktr** [Mr0grog/newless#18]
I noticed, that if I have a native class,

```js
class Foo {}
```

that when I `newless` it, the following applies:

```js
console.assert( Foo.prototype.constructor === Foo )

const _Foo = newless(Foo)

console.assert( _Foo.prototype === Foo.prototype )
console.assert( _Foo.prototype.constructor !== _Foo )
console.assert( _Foo.prototype.constructor === Foo )
```

What if _Foo has a new `prototype` so that

```js
console.assert( _Foo.prototype !== Foo.prototype )
console.assert( _Foo.prototype.constructor === _Foo )
console.assert( _Foo.prototype.constructor !== Foo )
```

? Would that ruin anything? What's the reason for not having a new prototype layer? Seems meaningful to have the new layer, because it isn't really the same class.

**Comment by trusktr** [comment]
The following can be confusing:

```js
const f = new _Foo()
console.assert( f instanceof _Foo )
console.assert( f.constructor !== _Foo)
```

`f`'s `constructor` is not `_Foo`.

Not yet sure how (or if) to change this in newless.

**Comment by Mr0grog** [comment]
> What's the reason for not having a new prototype layer? Seems meaningful to have the new layer, because it isn't really the same class…
> 
> The following can be confusing:
> ```js
> const f = new _Foo()
> console.assert( f instanceof _Foo )
> console.assert( f.constructor !== _Foo)
> ```

It’s been a long time, but IIRC, I did this to try and make instances created from a newless constructor transparently swappable with non-newless ones, so you couldn’t tell the difference between them. That is, I was looking at it more from this perspective:

```js
const originalF = new Foo()
const newlessF = new _Foo()
console.assert( newlessF.constructor === originalF.constructor )
console.assert( Object.getPrototypeOf(newlessF) === Object.getPrototypeOf(originalF) )
```

That might be weird, but it allows you to newless-ify things in the middle of an inheritance chain after the fact, making library objects from a non-newless toolset compatible with local ones you’ve newless-ified:

```js
class A {}
class B extends A {}
const bInstance = new B();
console.assert( bInstance instanceof A );

const NewlessA = newless(A);
console.assert( bInstance instanceof NewlessA);
```

Or to put it another way: the idea I had with newless wasn’t to create a conceptually new version of a class that didn’t require `new`. It was to make it possible to construct an existing class without `new`. Or a new *entry point* to the thing you already have rather than a whole new thing (even if it’s technically a whole new thing behind the scenes).

…but I can’t really say whether the weirdness required for that is necessarily better than the simplicity of effectively creating a whole new class that inherits from the non-newless one. If someone actively using the library felt this was causing them real trouble, I wouldn’t be super opposed to changing it. But it *is* this way for a reason.

**Comment by trusktr** [comment]
Cool, I've changed it in my case to return a new class. See here: https://github.com/trusktr/lowclass/blob/master/src/newless.js

But in the process I've also removed `TRUE_CONSTRUCTOR` which happens to work for my simple use cases so far, but I haven't tried other cases where we go from newless class to native class and back to newless class in the inheritance chain. So far I'm just using newless classes as base classes, which seems to be ok.
